name: birthdays
description: "Be notified of birthdays for the current and next year."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  android_alarm_manager_plus: ^4.0.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.1
  flutter_sticky_header: ^0.8.0
  flutter_timezone: ^4.1.1
  intl: ^0.20.2
  month_picker_dialog: ^6.3.0
  path: ^1.9.0
  permission_handler: ^12.0.1
  provider: ^6.1.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.3
  sqflite: ^2.0.2+1
  table_calendar: ^3.0.9
  timezone: ^0.10.1

dev_dependencies:
  android_notification_icons: ^0.0.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

android_notification_icons:
  image_path: assets/images/ic_launcher.png

flutter:
  uses-material-design: true
